<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>..\..\assets\brand\zenui-icon.ico</ApplicationIcon>
    <RootNamespace>ZenUI.Wpf.Gallery</RootNamespace>
    <AssemblyName>ZenUI.Wpf.Gallery</AssemblyName>
    <StartupObject>ZenUI.Wpf.Gallery.Program</StartupObject>
    <LangVersion>8.0</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.4" />
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
    <ProjectReference Include="..\..\src\ZenUI.Wpf\ZenUI.Wpf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
